### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tuomitie** [Corned/PacMan-DIY#3]
PacMan-DIY - ladattu 18.2.2017 n. klo 13

Kokonaisuutena vaikuttava projekti: Tekijällä on selvästi ollut aika hyvä kuva siitä, miten haluaa työtä lähteä toteuttamaan. Ydintoiminnallisuus on jo kunnossa, mutta joudutaanko kunnianhimoisimmista featureista (kenttäeditori) tinkimään aikataulun vuoksi?

Reaaliaikaisten pelien toteutus ja etenkin monimutkaisemmat reitinetsimismenetelmät ovat vielä oman ymmärrykseni tavoittamattomissa, joten seuraavat huomiot ovat PacMan-DIY:stä yleensä.

* Dokumentointi tosi hyvällä tasolla. Luokkakaaviossa tosin on aika paljon kamaa. Voisiko siitä siivota esim. UI-elementtejä pois? Tykkään tavoitteista ja saavutuksista tuntikirjanpidossa.
* Projektin rakenne on selkeä, ja pakkausten käyttö esimerkillistä.
* Pelin visuaalinen ilme ja toiminta kondiksessa. Pelatessa vähän ärsyttää kun PacMan jumittaa kääntyessä nurkkiin, mutta kuka sanoi että kummituksilta pakenemisen pitäisi olla helppoa?
* Kommentteja voisi viljellä koodin seassa tiheämpään. Esimerkkinä PathfindingService-luokka, jonka toiminnasta minulla ei ollut aavistustakaan, olisi kaivannut reilusti rivikommentteja auetakseen.
* Osa metodeista on tosi pitkiä, ja em. luokassa pathfind-metodia selventäisi myös sen pilkkominen osiin. Entä Game-luokan actionPerformed-metodi? Voisiko se käyttää apumetodeja?
* Maallikon silmin kunkin kummituksen luokassa on hämmästyttävän paljon tavaraa. Äkkiseltään ajattelisin että liikkumisen ja luonteen erityispiirteet mahtuisivat paljon pienempäänkin tilaan. Kummitusten refaktorointi olikin jo suunnitelmissa. Voisiko siinä yhteydessä ottaa ohjelmointihaasteeksi tehdä Blinky-, Clyde-, Inky- ja Pinky-luokista mahdollisimman ytimekkäät?

Hyvä meininki!

**Comment by Corned** [comment]
Kiitos kattavasta palautteesta.

- Omastakin mielestäni luokkakaavio on jopa sotkuinen. Paremmalla luokkien sijoittelulla tämän pitäisi korjaantua.
- Kiitos <3
- Minuakin hieman ärsyttää kun PacMan jää seinään jumiin. Alkuperäisessä PacMan-pelissä PacMan liikkui ikään kuin raiteilla, toisin kuin omassa toteutuksessani. Minulla on pieni idea siitä, miten jumittumisen voisi korjana. Saa nähdä toteutuuko idea.
- Kyllä, kommentit. Aivan samaa mieltä. 
- Pathfind- ja actionPerformed-metodit ovat todellakin aivan liian pitkiä. actionPerformed-metodia olenkin jo hieman lyhentänyt.
- Blinky-, Pinky-, Inky- ja Clyde-luokkien update-metodin toiminnallisuuksia on jo siirrettykin näiden superluokkaan, Ghostiin. Vielä on kuitenkin refaktoroitavaa.

Kenttäeditorin kanssa saattaa tulla aikaraja vastaan, mutta jos aukaiset pelin jar-tiedoston esim. winrar-ohjelmalla, voit sieltä käsin editoita pelikenttiä. ;)

Kiitos vielä kerran kattavasta palautteesta.
